export const meetupConstants = {
  SET_TEXT_FILTER: "SET_TEXT_FILTER",
  SET_TYPE_FILTER: "SET_TYPE_FILTER",
  SET_SHOW_RSVP_MODAL: "SET_SHOW_RSVP_MODAL",
  SET_SELECTED_MEETUP: "SET_SELECTED_MEETUP",
  SET_RSVP_MEETUP: "SET_RSVP_MEETUP",
};
